# Generated by Django 4.1.3 on 2023-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_member_firstname_remove_member_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='attrite',
        ),
        migrations.RemoveField(
            model_name='member',
            name='avgOpenToBuy',
        ),
        migrations.RemoveField(
            model_name='member',
            name='avgUtilizationRatio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='children',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contactsCount12mon',
        ),
        migrations.RemoveField(
            model_name='member',
            name='creditLimit',
        ),
        migrations.RemoveField(
            model_name='member',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='income',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marital',
        ),
        migrations.RemoveField(
            model_name='member',
            name='monthOnBooks',
        ),
        migrations.RemoveField(
            model_name='member',
            name='monthsInactive12mon',
        ),
        migrations.RemoveField(
            model_name='member',
            name='totalAmtChngQ4Q1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='totalCtChngQ4Q1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='totalRelationshipCount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='totalRevolvingBal',
        ),
        migrations.RemoveField(
            model_name='member',
            name='totalTransAmt',
        ),
        migrations.RemoveField(
            model_name='member',
            name='totalTransCt',
        ),
        migrations.AddField(
            model_name='member',
            name='caa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='chol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='exng',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='fbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='restecg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='member',
            name='thalachh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='trtbps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='incognito', max_length=20),
        ),
    ]
